1. Подберите скорость обучения (alpha) и количество итераций для достижения минимальног значения функции потерь;
2.  (опция). В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

for i in range(1000):
y_pred = np.dot(W, X)
err = calc_mse(y, y_pred)
'''for ii in range(W.shape[0]):
W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
W -= (alpha * (1/n * 2 * np.sum(X * (y_pred - y))))
if i % 100 == 0:
print(i, W, err)

3. (опция). Реализовать один из критериев останова, перечисленный в методичке.

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
y = [45, 55, 50, 59, 65, 35, 75, 80, 50, 60]

In [4]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2]])
X.shape

(2, 10)

In [12]:
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_squared_error as mse

In [15]:
mae_1 = np.mean(np.abs(y - y_pred1))
mae_2 = np.mean(np.abs(y - y_pred2))

In [16]:
mae_1, mae_2

(10.4, 7.9)

In [17]:
mse_1 = np.mean((y - y_pred1)**2)
mse_2 = np.mean((y - y_pred2)**2)

In [18]:
mse_1, mse_2

(143.6, 151.35)

Метод наименьших квадратов

In [22]:
X.shape

(2, 10)

In [23]:
X.T.shape

(10, 2)

In [25]:
W = np.linalg.inv(np.dot(X, X.T)) @ X @ y
W

array([47.23214286,  3.91071429])

In [28]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [29]:
calc_mse(y, y_pred1)

143.6

In [30]:
def calc_mae(y, y_pred):
    err = np.mean(np.abs(y - y_pred))
    return err

In [31]:
calc_mae(y, y_pred1)

10.4

In [32]:
y_pred3 = W[0] + W[1] * X[1]
y_pred3

array([51.14285714, 51.14285714, 55.05357143, 51.14285714, 58.96428571,
       47.23214286, 66.78571429, 86.33928571, 51.14285714, 55.05357143])

In [33]:
# RMSE - root mean squared error
np.sqrt(calc_mse(y, y_pred3))

6.777720855862979

In [34]:
calc_mae(y, y_pred3)

6.182142857142858

In [35]:
mse_old = 10.32
mse_new = 10.3199999

delta = 0.1

Градиентный спуск

In [37]:
n = 10
f = 1/n * np.sum((W[0] * X[0] - y)**2)

In [38]:
alpha = 1e-8
g = alpha * (1/n * 2 * np.sum(X[0] * (W[0] * X[0] - y)))

In [39]:
W[0] - g

47.232143060499986

1. Подберите скорость обучения (alpha) и количество итераций:

In [84]:
n = X.shape[1]
alpha = 1e-4
W = np.array([1, 0.5])
W, alpha

(array([1. , 0.5]), 0.0001)

In [85]:
gradient_1 = alpha * (1/n * 2 * np.sum(X[0] * W[0] - y[0]))
print(gradient_1)
print(W[0] - gradient_1)

-0.0088
1.0088


In [89]:
for i in range(2000):
    y_pred = np.dot(W, X)
    err = calc_mae(y, y_pred)
    for ii in range(W.shape[0]):
        W[ii] -= 1e-2 * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))
        if i % 200 == 0:
            print(i, W, err)

0 [47.23214286  3.91071429] 6.182142857142869
0 [47.23214286  3.91071429] 6.182142857142869
200 [47.23214286  3.91071429] 6.182142857142869
200 [47.23214286  3.91071429] 6.182142857142869
400 [47.23214286  3.91071429] 6.182142857142869
400 [47.23214286  3.91071429] 6.182142857142869
600 [47.23214286  3.91071429] 6.182142857142869
600 [47.23214286  3.91071429] 6.182142857142869
800 [47.23214286  3.91071429] 6.182142857142869
800 [47.23214286  3.91071429] 6.182142857142869
1000 [47.23214286  3.91071429] 6.182142857142869
1000 [47.23214286  3.91071429] 6.182142857142869
1200 [47.23214286  3.91071429] 6.182142857142869
1200 [47.23214286  3.91071429] 6.182142857142869
1400 [47.23214286  3.91071429] 6.182142857142869
1400 [47.23214286  3.91071429] 6.182142857142869
1600 [47.23214286  3.91071429] 6.182142857142869
1600 [47.23214286  3.91071429] 6.182142857142869
1800 [47.23214286  3.91071429] 6.182142857142869
1800 [47.23214286  3.91071429] 6.182142857142869


*2. В этом коде мы избавляемся от итераций по весам, но тут есть ошибка, исправьте ее:

In [87]:
for i in range(2000):
    y_pred = np.dot(W, X)
    err = calc_mae(y, y_pred)
    '''for ii in range(W.shape[0]):
    W[ii] -= alpha * (1/n * 2 * np.sum(X[ii] * (y_pred - y)))'''
    W -= (1e-2 * (1/n * 2 * np.dot((y_pred - y), X.T)))
    if i % 200 == 0:
        print(i, W, err)

0 [47.23214282  3.91071429] 6.18214285850156
200 [47.23214285  3.91071429] 6.182142857310835
400 [47.23214286  3.91071429] 6.182142857163624
600 [47.23214286  3.91071429] 6.182142857145424
800 [47.23214286  3.91071429] 6.182142857143175
1000 [47.23214286  3.91071429] 6.182142857142898
1200 [47.23214286  3.91071429] 6.182142857142869
1400 [47.23214286  3.91071429] 6.182142857142869
1600 [47.23214286  3.91071429] 6.182142857142869
1800 [47.23214286  3.91071429] 6.182142857142869
