Домашнее задание:
1. Задание 1: Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.
2. Задание 2: Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.
3. Задание 3: Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).
4. Задание 4: Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).
5. Задание 5: Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.
6. Задание 6: Могла ли модель переобучиться? Почему?
7. Задание 7 (опциональное): Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [50]:
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt

%matplotlib inline

Задание 1: Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [51]:
def calc_logloss(y_true, y_pred):
    k = 1e-5
    y_pred = y_pred.copy()
    y_pred = np.clip(y_pred, a_min=k, a_max=1-k)
    err = - np.mean(y_true * np.log(y_pred) + (1.0 - y_true) * np.log(1.0 - y_pred))
    return err

Задание 2: Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [52]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450,
               800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 
               1, 3, 3, 1, 2]], dtype = np.float64)

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [53]:
X

array([[1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00,
        1.00e+00, 1.00e+00, 1.00e+00, 1.00e+00],
       [1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00, 3.00e+00, 0.00e+00,
        5.00e+00, 1.00e+01, 1.00e+00, 2.00e+00],
       [5.00e+02, 7.00e+02, 7.50e+02, 6.00e+02, 1.45e+03, 8.00e+02,
        1.50e+03, 2.00e+03, 4.50e+02, 1.00e+03],
       [1.00e+00, 1.00e+00, 2.00e+00, 1.00e+00, 2.00e+00, 1.00e+00,
        3.00e+00, 3.00e+00, 1.00e+00, 2.00e+00]])

In [54]:
y

array([0., 0., 1., 0., 1., 0., 1., 0., 1., 1.])

In [55]:
def calc_std_feat(x):
    x[1:] = ((x[1:].T - x[1:].mean(axis=1)) / x[1:].std(axis=1)).T
    return x

In [56]:
x = calc_std_feat(X)

In [57]:
def calc_std_feat(X):
    X_tr = X[1:,].copy()
    X_mean, X_std = X_tr.mean(axis=1), X_tr.std(axis=1)
    X_mean, X_std = X_mean.reshape(X_tr.shape[0], 1), X_std.reshape(X_tr.shape[0], 1)
    X_tr = (X_tr - X_mean)/X_std
    X_tr = np.vstack((np.ones(X_tr.shape[1]), X_tr))
    return X_tr

In [58]:
def sigmoid(z):
    rec = 1 / (1 + np.exp(-z))
    return rec

In [59]:
def eval_model(X, y, iteration, alpha=1e-4, k=1e-5):
    np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    err = []
    w = []
    
    for n_iter in range (1, iteration+1):
        z = np.dot(W, X)
        y_pred = sigmoid(z)
        err_new = calc_logloss(y, y_pred)
        W = W - alpha*(1/n * np.dot((y_pred - y), X.T))
        #W -= alpha * (1/n * np.dot((y_pred - y), X.T))
        err.append(err_new)
        w.append(W)
        
        if n_iter > 2 and np.abs(err_new - err[-2]) < k:
            print(n_iter, W, err_new)
            break
    err = np.array(err)
    return err, w

In [60]:
learning_model = [0.1, 0.01, 0.001, 0.0001]

for alpha1 in learning_model:
    W = eval_model(X, y, iteration=1000000, alpha=alpha1)

6236 [ 1.80385313 -5.00023322 -4.03203415 10.50060735] 0.20882355724960683
6193 [ 0.22322901 -2.33314778 -0.81934289  3.73020567] 0.3379492576690167
5495 [ 0.19641082 -0.94005846 -0.0076054   1.43621037] 0.49456917344192275
8140 [ 0.45930427 -0.33157412  0.47217682  1.43686081] 0.6690360538916054


In [61]:
for alpha in [0.1, 0.01, 0.001, 0.0001]:
    err_1, w_1 = eval_model(X=X, y=y, iteration = 1000000, alpha=alpha)

6236 [ 1.80385313 -5.00023322 -4.03203415 10.50060735] 0.20882355724960683
6193 [ 0.22322901 -2.33314778 -0.81934289  3.73020567] 0.3379492576690167
5495 [ 0.19641082 -0.94005846 -0.0076054   1.43621037] 0.49456917344192275
8140 [ 0.45930427 -0.33157412  0.47217682  1.43686081] 0.6690360538916054


3. Задание 3: Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [62]:
def calc_pred_proba(W, X):
    y_pred = 1 /(1+ np.exp(-np.dot(W, X)))
    return y_pred

In [63]:
calc_pred_proba(w_1[-1], X)

array([0.24944723, 0.28765324, 0.70332289, 0.26811923, 0.80633815,
       0.33380776, 0.95597403, 0.95132722, 0.24044325, 0.75149724])

Задание 4: Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [64]:
def calc_pred(W, X, threshold=0.5):
    y_pred = calc_pred_proba(W, X)
    y_pred = np.where(y_pred > threshold, 1, 0)
    return y_pred

In [65]:
y_pred = calc_pred(w_1[-1], X)
y_pred

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 1])

Задание 5: Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [68]:
def confusion_matrix(y, y_pred):
    conf_matrix = np.zeros(shape=(2,2))
    # находим значение tp
    conf_matrix[0,0] = np.sum(np.where(y==1,y==y_pred,False))
    # находим значение tn
    conf_matrix[1,1] = np.sum(np.where(y==0,y==y_pred,False))
    # находим значение fn
    conf_matrix[1,0] = np.sum(np.where(y==1,y!=y_pred,False))
    # находим значение fp
    conf_matrix[0,1] = np.sum(np.where(y==0,y!=y_pred,False))
    
    return conf_matrix.astype(int)

In [69]:
conf_matrix = confusion_matrix(y, y_pred)
conf_matrix

array([[4, 1],
       [1, 4]])

In [70]:
def accuracy_score (y, y_pred):
    tp, tn, fn, fp = conf_matrix.flatten()
    accuracy = (tp + tn) / (tp + tn + fp + fn)
    return accuracy

In [71]:
accuracy = accuracy_score(y, y_pred)
accuracy

0.5

In [72]:
def preсision_score (y, y_pred):            
    tp, tn, fn, fp = conf_matrix.flatten()
    preсision = tp /(tp + fp)
    return preсision

In [73]:
preсision = preсision_score (y, y_pred)
preсision

0.5

In [74]:
def recall_score (y, y_pred):
    tp, tn, fn, fp = conf_matrix.flatten()
    recall = tp / (tp + fn)
    return recall

In [75]:
recall = recall_score(y, y_pred)
recall

0.8

In [76]:
def f1_score (y, y_pred):            
    tp, tn, fn, fp = conf_matrix.flatten()
    f1 = 2 * preсision * recall / (preсision + recall)
    return f1

In [77]:
f1 = f1_score (y, y_pred)
f1

0.6153846153846154